language: ruby
rvm:
- 2.3.3

before_script:

script:
  - set -e
  - bundle exec jekyll build
  - htmlproofer --assume-extension ./_site --url-swap "https?\:\/\/(localhost\:4000|):"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
