
title: OpenMTR
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for OpenMTR.
baseurl: ''
url: "OpenMTR.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  OpenMTR

disqus:
  shortname: OpenMTR

markdown: kramdown

paginate:         5
# paginate_path:    '/page:num'

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
