
title: OpenMTR
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for OpenMTR.
baseurl: "" # the subpath of your site, e.g. /blog
url: "OpenMTR.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  OpenMTR

disqus:
  shortname: OpenMTR

markdown: kramdown

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
